name: xmpp_stone

description: "Xmpp Stone is lightweight XMPP client library written completely in Dart."

version: 0.3.5

homepage: https://vukoye.github.io

environment:
  sdk: '>=2.12.0 <3.0.0'

#dependencies:
#  path: ^1.4.1
dependencies:
  xml: ^5.3.1
  cryptoutils: ^0.5.0
  crypto: ^3.0.1
  synchronized: ^3.0.0
  tuple: ^2.0.0
  unorm_dart: ^0.2.0
  image: ^3.1.3
  quiver: ^3.0.0 #hash code generator
  console: ^3.1.0 #for example
  intl: ^0.17.0

dev_dependencies:
  test: ^1.0.0
  mockito: ^4.0.0
